### ISSUE TITLE
[chore] Поиск хостинга под wordpress

### ISSUE THREAD

**Issue by aenoralanar** [torin-asakura/wordpress#3]
Необходимо найти хостинг провайдера с поддержкой tf.

**Comment by aenoralanar** [comment]
Непосредственно shared хостингов с поддержкой tf найти не удалось. Хорошим вариантами будут(выше, имхо, лучше):
- linode
- DO
- vultr

**Comment by TorinAsakura** [comment]
> Непосредственно shared хостингов с поддержкой tf найти не удалось. Хорошим вариантами будут(выше, имхо, лучше):
> 
> * linode
> * DO
> * vultr

выбрал linode
надо разворачиваться
